# -*- coding: utf-8 -*-
"""Train and tune BCC-CSM2-MR XGBoost models for lightning and hail frequency.

This script is adapted from the author's final checked BCC-CSM2-MR notebook.
It uses the historical feature parquet generated by ``bcc_01_build_features.py``
and performs:

- removal of seasonal features from the training candidate set;
- a fixed 70/15/15 random train/validation/test split;
- full-feature gain ranking;
- TopK feature-number sensitivity tests;
- XGBoost hyperparameter sensitivity tests;
- separate final models for lightning (legacy internal name ``FLASH``) and hail.

Run from the repository root with::

    python -m modeling.bcc_02_train
"""

from __future__ import annotations

from publication_config import resource_path

import itertools
import json
import os
import time
from copy import deepcopy
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


# =========================================================
# 0) PATHS & CONFIG
# =========================================================
MODEL_NAME = "BCC-CSM2-MR"
BASE_DIR = Path(resource_path("models", "BCC-CSM2-MR"))

FEATURE_HIST = (
    BASE_DIR
    / "feature"
    / "ml_train_historical"
    / "features_historical_2012_2014.parquet"
)
LABEL_STRICT = (
    BASE_DIR
    / "feature"
    / "ml_train_historical"
    / "labels_land_strict.parquet"
)

# bcc_03_standardize.py scans this directory for FLASH_* and HAIL_* runs.
RUN_ROOT = BASE_DIR / "TUNING_XGB"
RUN_ROOT.mkdir(parents=True, exist_ok=True)

TARGET_FLASH = "LISOTD_Flash"
TARGET_HAIL = "ni_HailPF"
LAT_COL = "Latitude"
LON_COL = "Longitude"

# Fixed split used in the original BCC workflow.
SEED = 42
TEST_SIZE = 0.15
VALID_SIZE = 0.15

CLIP_NEGATIVE_PRED = True
RUN_SENSITIVITY_TEST = True
RUN_TOPK_TEST = True

# Final checked notebook configuration.
TOPK_LIST = [60, 90, 120, 150]

XGB_BASE_PARAMS = {
    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "eta": 0.03,
    "max_depth": 6,
    "min_child_weight": 3,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "lambda": 1.0,
    "alpha": 0.0,
    "tree_method": "hist",
    "seed": SEED,
}

# Parameter grid preserved from the author's final checked notebook.
PARAM_GRID = {
    "eta": [0.03, 0.05],
    "max_depth": [3, 4, 5],
    "min_child_weight": [3, 5, 8],
    "subsample": [0.7, 0.8],
    "colsample_bytree": [0.6, 0.8],
    "lambda": [1.0, 5.0, 10.0],
    "alpha": [0.0, 0.5],
}

NUM_BOOST_ROUND = 3000
EARLY_STOPPING_ROUNDS = 100
VERBOSE_EVAL_FINAL = 100
VERBOSE_EVAL_TUNING = False


# =========================================================
# 1) UTILITIES
# =========================================================
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


def metrics_dict(y_true, y_pred):
    return {
        "r2": float(r2_score(y_true, y_pred)),
        "rmse": float(rmse(y_true, y_pred)),
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "n": int(len(y_true)),
    }


def safe_mkdir(path: str | Path):
    Path(path).mkdir(parents=True, exist_ok=True)


def timestamp():
    return time.strftime("%Y%m%d_%H%M%S")


def file_exists_or_raise(path: str | Path, what: str):
    if not Path(path).exists():
        raise FileNotFoundError(f"{what} not found: {path}")


def choose_feature_columns(df: pd.DataFrame) -> list[str]:
    """Keep annual ``env_*`` features and ``elev``; exclude seasonal features."""
    out = []
    for c in df.columns:
        if c == "elev":
            out.append(c)
            continue
        if not str(c).startswith("env_"):
            continue
        if any(tag in c for tag in ("_DJF_", "_MAM_", "_JJA_", "_SON_")):
            continue
        out.append(c)
    return sorted(out)


def get_best_iteration(model: xgb.Booster) -> int:
    """Return zero-based best iteration with compatibility handling."""
    best_iter = getattr(model, "best_iteration", None)
    if best_iter is not None:
        return int(best_iter)
    return int(model.num_boosted_rounds() - 1)


def predict_with_best(model: xgb.Booster, dmat: xgb.DMatrix) -> np.ndarray:
    """Predict using the best iteration, compatible with common XGBoost versions."""
    best_iter = get_best_iteration(model)
    try:
        return model.predict(dmat, iteration_range=(0, best_iter + 1))
    except TypeError:
        best_ntree_limit = getattr(model, "best_ntree_limit", None)
        if best_ntree_limit is not None and best_ntree_limit > 0:
            return model.predict(dmat, ntree_limit=best_ntree_limit)
        return model.predict(dmat)


def make_param_combinations(param_grid: dict) -> list[dict]:
    keys = list(param_grid.keys())
    vals = [param_grid[k] for k in keys]
    return [dict(zip(keys, one)) for one in itertools.product(*vals)]


def normalize_topk_list(topk_list: list, n_features: int) -> list[tuple[str, int]]:
    """Convert requested TopK values into unique, valid feature counts."""
    out = []
    seen_k = set()

    for item in topk_list:
        if isinstance(item, str) and item.lower() == "all":
            k = n_features
            label = "All"
        else:
            requested = int(item)
            k = min(requested, n_features)
            label = f"Top{requested}" if requested <= n_features else f"Top{requested}_actual{k}"

        if k <= 0 or k in seen_k:
            continue
        seen_k.add(k)
        out.append((label, k))

    if not out:
        out = [("All", n_features)]
    return out


# =========================================================
# 2) LOAD TABLES & SPLIT
# =========================================================
def load_train_table(feature_hist: str | Path, label_strict: str | Path, target_col: str):
    file_exists_or_raise(feature_hist, "historical feature parquet")
    file_exists_or_raise(label_strict, "strict-land label parquet")

    df_feat = pd.read_parquet(feature_hist)
    df_lab = pd.read_parquet(label_strict)

    need_cols = [LAT_COL, LON_COL, target_col]
    missing_lab = [c for c in need_cols if c not in df_lab.columns]
    if missing_lab:
        raise ValueError(f"label_strict is missing columns: {missing_lab}")
    df_lab = df_lab[need_cols].copy()

    df = df_lab.merge(df_feat, on=[LAT_COL, LON_COL], how="inner")

    feat_cols = choose_feature_columns(df)
    if not feat_cols:
        raise ValueError("No candidate env_* or elev features were found.")

    keep_cols = [LAT_COL, LON_COL, target_col] + feat_cols
    df = df[keep_cols].copy().replace([np.inf, -np.inf], np.nan)

    before = len(df)
    df = df.dropna(subset=[target_col] + feat_cols).reset_index(drop=True)
    after = len(df)

    print(f"[{target_col}] merged rows   : {before}")
    print(f"[{target_col}] rows after NA : {after}")
    print(f"[{target_col}] n_features    : {len(feat_cols)}")

    return df, feat_cols


def make_split_indices(df: pd.DataFrame):
    """Create one fixed train/validation/test split for all tuning trials."""
    idx = np.arange(len(df))

    idx_train_valid, idx_test = train_test_split(
        idx, test_size=TEST_SIZE, random_state=SEED
    )

    valid_ratio_inside = VALID_SIZE / (1.0 - TEST_SIZE)
    idx_train, idx_valid = train_test_split(
        idx_train_valid, test_size=valid_ratio_inside, random_state=SEED
    )

    return idx_train, idx_valid, idx_test


def make_xy_from_indices(
    df: pd.DataFrame,
    feature_cols: list[str],
    target_col: str,
    split_indices: tuple[np.ndarray, np.ndarray, np.ndarray],
):
    idx_train, idx_valid, idx_test = split_indices

    X_train = df.loc[idx_train, feature_cols].copy()
    X_valid = df.loc[idx_valid, feature_cols].copy()
    X_test = df.loc[idx_test, feature_cols].copy()

    y_train = df.loc[idx_train, target_col].copy()
    y_valid = df.loc[idx_valid, target_col].copy()
    y_test = df.loc[idx_test, target_col].copy()

    return X_train, X_valid, X_test, y_train, y_valid, y_test


def make_dmats(X_train, X_valid, X_test, y_train, y_valid, y_test, feature_cols: list[str]):
    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=feature_cols)
    dvalid = xgb.DMatrix(X_valid, label=y_valid, feature_names=feature_cols)
    dtest = xgb.DMatrix(X_test, label=y_test, feature_names=feature_cols)
    return dtrain, dvalid, dtest


def save_split_tables(X_train, X_valid, X_test, y_train, y_valid, y_test, target_col: str, out_dir: str | Path):
    out_dir = Path(out_dir)
    pd.concat([X_train.reset_index(drop=True), y_train.reset_index(drop=True)], axis=1).to_parquet(
        out_dir / "train_table.parquet", index=False
    )
    pd.concat([X_valid.reset_index(drop=True), y_valid.reset_index(drop=True)], axis=1).to_parquet(
        out_dir / "valid_table.parquet", index=False
    )
    pd.concat([X_test.reset_index(drop=True), y_test.reset_index(drop=True)], axis=1).to_parquet(
        out_dir / "test_table.parquet", index=False
    )


# =========================================================
# 3) FEATURE RANKING
# =========================================================
def rank_features_by_full_gain(
    df: pd.DataFrame,
    all_feature_cols: list[str],
    target_col: str,
    split_indices: tuple[np.ndarray, np.ndarray, np.ndarray],
    out_dir: str | Path,
) -> tuple[list[str], str]:
    """Rank all candidate features by gain from a full-feature reference model."""
    print(f"\n[RANK] {target_col}: train full-feature reference model for TopK ranking ...")

    X_train, X_valid, X_test, y_train, y_valid, y_test = make_xy_from_indices(
        df=df,
        feature_cols=all_feature_cols,
        target_col=target_col,
        split_indices=split_indices,
    )
    dtrain, dvalid, _ = make_dmats(
        X_train, X_valid, X_test, y_train, y_valid, y_test, all_feature_cols
    )

    ranking_params = deepcopy(XGB_BASE_PARAMS)
    ranking_params["seed"] = SEED

    ranking_model = train_booster(
        params=ranking_params,
        dtrain=dtrain,
        dvalid=dvalid,
        verbose_eval=False,
    )

    imp_gain = ranking_model.get_score(importance_type="gain")
    df_rank = pd.DataFrame(
        {
            "feature": all_feature_cols,
            "gain": [float(imp_gain.get(c, 0.0)) for c in all_feature_cols],
        }
    )
    df_rank = df_rank.sort_values(
        by=["gain", "feature"], ascending=[False, True]
    ).reset_index(drop=True)
    df_rank["rank"] = np.arange(1, len(df_rank) + 1)

    out_csv = str(Path(out_dir) / f"feature_ranking_gain_full_features_{target_col}.csv")
    df_rank.to_csv(out_csv, index=False, encoding="utf-8-sig")

    print(f"[RANK] Saved: {out_csv}")
    return df_rank["feature"].tolist(), out_csv


# =========================================================
# 4) TRAIN / EVALUATE
# =========================================================
def train_booster(params: dict, dtrain: xgb.DMatrix, dvalid: xgb.DMatrix, verbose_eval=False) -> xgb.Booster:
    evals = [(dtrain, "train"), (dvalid, "valid")]
    return xgb.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=NUM_BOOST_ROUND,
        evals=evals,
        early_stopping_rounds=EARLY_STOPPING_ROUNDS,
        verbose_eval=verbose_eval,
    )


def evaluate_model(
    model: xgb.Booster,
    dtrain: xgb.DMatrix,
    dvalid: xgb.DMatrix,
    dtest: xgb.DMatrix,
    y_train: pd.Series,
    y_valid: pd.Series,
    y_test: pd.Series,
):
    pred_train = predict_with_best(model, dtrain)
    pred_valid = predict_with_best(model, dvalid)
    pred_test = predict_with_best(model, dtest)

    if CLIP_NEGATIVE_PRED:
        pred_train = np.clip(pred_train, 0, None)
        pred_valid = np.clip(pred_valid, 0, None)
        pred_test = np.clip(pred_test, 0, None)

    metrics = {
        "best_iteration": int(get_best_iteration(model)),
        "train": metrics_dict(y_train, pred_train),
        "valid": metrics_dict(y_valid, pred_valid),
        "test": metrics_dict(y_test, pred_test),
    }
    return metrics, pred_train, pred_valid, pred_test


def sensitivity_test(
    target_col: str,
    df: pd.DataFrame,
    ranked_features: list[str],
    all_feature_cols: list[str],
    split_indices: tuple[np.ndarray, np.ndarray, np.ndarray],
    ranking_csv: str | None,
    out_dir: str | Path,
):
    out_dir = Path(out_dir)
    param_combos = make_param_combinations(PARAM_GRID)

    if RUN_TOPK_TEST:
        topk_pairs = normalize_topk_list(TOPK_LIST, len(ranked_features))
    else:
        topk_pairs = [("All", len(all_feature_cols))]
        ranked_features = all_feature_cols

    n_param_trials = len(param_combos)
    n_total_trials = n_param_trials * len(topk_pairs)

    print(f"\n[TUNING] {target_col}: TopK candidates = {topk_pairs}")
    print(f"[TUNING] {target_col}: parameter combos = {n_param_trials}")
    print(f"[TUNING] {target_col}: total trials = {n_total_trials}")

    rows = []
    trial_id = 0
    t0 = time.time()

    for topk_label, actual_k in topk_pairs:
        selected_features = ranked_features[:actual_k]

        topk_feat_csv = out_dir / f"feature_columns_{target_col}_{topk_label}.csv"
        pd.DataFrame({"feature": selected_features}).to_csv(
            topk_feat_csv, index=False, encoding="utf-8-sig"
        )

        X_train, X_valid, X_test, y_train, y_valid, y_test = make_xy_from_indices(
            df=df,
            feature_cols=selected_features,
            target_col=target_col,
            split_indices=split_indices,
        )
        dtrain, dvalid, dtest = make_dmats(
            X_train, X_valid, X_test, y_train, y_valid, y_test, selected_features
        )

        for override in param_combos:
            trial_id += 1
            params = deepcopy(XGB_BASE_PARAMS)
            params.update(override)
            params["seed"] = SEED

            model = train_booster(params, dtrain, dvalid, verbose_eval=VERBOSE_EVAL_TUNING)
            metrics, _, _, _ = evaluate_model(
                model, dtrain, dvalid, dtest, y_train, y_valid, y_test
            )

            train_r2 = metrics["train"]["r2"]
            valid_r2 = metrics["valid"]["r2"]
            test_r2 = metrics["test"]["r2"]

            row = {
                "target": target_col,
                "trial": trial_id,
                "topk_label": topk_label,
                "actual_topk": int(actual_k),
                "n_all_features": int(len(all_feature_cols)),
                "topk_feature_columns_csv": str(topk_feat_csv),
                "feature_ranking_csv": ranking_csv,
                "best_iteration": metrics["best_iteration"],
                "train_r2": train_r2,
                "valid_r2": valid_r2,
                "test_r2": test_r2,
                "train_rmse": metrics["train"]["rmse"],
                "valid_rmse": metrics["valid"]["rmse"],
                "test_rmse": metrics["test"]["rmse"],
                "train_mae": metrics["train"]["mae"],
                "valid_mae": metrics["valid"]["mae"],
                "test_mae": metrics["test"]["mae"],
                "overfit_gap_train_valid": float(train_r2 - valid_r2),
                "abs_valid_test_r2_gap": float(abs(valid_r2 - test_r2)),
            }
            row.update(override)
            rows.append(row)

            if (trial_id % 10 == 0) or (trial_id == 1) or (trial_id == n_total_trials):
                elapsed_min = (time.time() - t0) / 60.0
                print(
                    f"[{target_col}] [{trial_id}/{n_total_trials}] "
                    f"{topk_label} | valid_r2={valid_r2:.4f}, test_r2={test_r2:.4f}, "
                    f"valid_rmse={metrics['valid']['rmse']:.5f}, elapsed={elapsed_min:.1f} min"
                )

    df_trials = pd.DataFrame(rows)

    # This ordering is preserved from the author's latest checked BCC notebook.
    df_trials = df_trials.sort_values(
        by=["valid_r2", "valid_rmse", "abs_valid_test_r2_gap"],
        ascending=[False, True, True],
    ).reset_index(drop=True)

    out_csv = out_dir / f"tuning_results_{target_col}.csv"
    df_trials.to_csv(out_csv, index=False, encoding="utf-8-sig")

    best_row = df_trials.iloc[0].to_dict()
    best_params = deepcopy(XGB_BASE_PARAMS)
    for key in PARAM_GRID:
        best_params[key] = best_row[key]
    best_params["seed"] = SEED

    selected_topk_label = str(best_row["topk_label"])
    selected_topk_n = int(best_row["actual_topk"])
    selected_features = ranked_features[:selected_topk_n]

    best_json = {
        "target": target_col,
        "selection_rule": "max valid_r2, then min valid_rmse, then min abs_valid_test_r2_gap",
        "run_topk_test": RUN_TOPK_TEST,
        "topk_list": TOPK_LIST,
        "selected_topk_label": selected_topk_label,
        "selected_topk_n": selected_topk_n,
        "n_param_combinations": int(n_param_trials),
        "n_total_trials": int(n_total_trials),
        "n_all_features": int(len(all_feature_cols)),
        "best_row": best_row,
        "best_params": best_params,
        "selected_feature_columns": selected_features,
        "feature_ranking_csv": ranking_csv,
        "tuning_results_csv": str(out_csv),
    }
    with open(out_dir / f"best_params_{target_col}.json", "w", encoding="utf-8") as f:
        json.dump(best_json, f, ensure_ascii=False, indent=2)

    print(f"\n[BEST] {target_col}")
    print(json.dumps(best_json, ensure_ascii=False, indent=2))

    return best_params, selected_features, selected_topk_label, selected_topk_n, df_trials


def train_one_target(df: pd.DataFrame, all_feature_cols: list[str], target_col: str, out_dir: str | Path):
    out_dir = Path(out_dir)
    safe_mkdir(out_dir)

    all_feat_csv = out_dir / "feature_columns_all_candidates.csv"
    pd.DataFrame({"feature": all_feature_cols}).to_csv(
        all_feat_csv, index=False, encoding="utf-8-sig"
    )

    split_indices = make_split_indices(df)

    if RUN_SENSITIVITY_TEST and RUN_TOPK_TEST:
        ranked_features, ranking_csv = rank_features_by_full_gain(
            df=df,
            all_feature_cols=all_feature_cols,
            target_col=target_col,
            split_indices=split_indices,
            out_dir=out_dir,
        )
    else:
        ranked_features = all_feature_cols
        ranking_csv = None

    if RUN_SENSITIVITY_TEST:
        best_params, selected_features, selected_topk_label, selected_topk_n, _ = sensitivity_test(
            target_col=target_col,
            df=df,
            ranked_features=ranked_features,
            all_feature_cols=all_feature_cols,
            split_indices=split_indices,
            ranking_csv=ranking_csv,
            out_dir=out_dir,
        )
    else:
        best_params = deepcopy(XGB_BASE_PARAMS)
        best_params["seed"] = SEED
        selected_features = all_feature_cols
        selected_topk_label = "All"
        selected_topk_n = len(selected_features)
        with open(out_dir / f"best_params_{target_col}.json", "w", encoding="utf-8") as f:
            json.dump(
                {
                    "target": target_col,
                    "selection_rule": "RUN_SENSITIVITY_TEST=False; use XGB_BASE_PARAMS and all features",
                    "run_topk_test": False,
                    "selected_topk_label": selected_topk_label,
                    "selected_topk_n": selected_topk_n,
                    "best_params": best_params,
                },
                f,
                ensure_ascii=False,
                indent=2,
            )

    selected_feat_csv = out_dir / "feature_columns.csv"
    pd.DataFrame({"feature": selected_features}).to_csv(
        selected_feat_csv, index=False, encoding="utf-8-sig"
    )

    X_train, X_valid, X_test, y_train, y_valid, y_test = make_xy_from_indices(
        df=df,
        feature_cols=selected_features,
        target_col=target_col,
        split_indices=split_indices,
    )
    save_split_tables(
        X_train, X_valid, X_test, y_train, y_valid, y_test, target_col, out_dir
    )

    dtrain, dvalid, dtest = make_dmats(
        X_train, X_valid, X_test, y_train, y_valid, y_test, selected_features
    )

    print(
        f"\n[FINAL TRAIN] {target_col} | {selected_topk_label} "
        f"({selected_topk_n} features) ..."
    )
    final_model = train_booster(
        best_params, dtrain, dvalid, verbose_eval=VERBOSE_EVAL_FINAL
    )

    metrics, pred_train, pred_valid, pred_test = evaluate_model(
        final_model, dtrain, dvalid, dtest, y_train, y_valid, y_test
    )

    metrics_out = {
        "model_name": MODEL_NAME,
        "target": target_col,
        "best_iteration": metrics["best_iteration"],
        "train": metrics["train"],
        "valid": metrics["valid"],
        "test": metrics["test"],
        "n_all_features": int(len(all_feature_cols)),
        "selected_topk_label": selected_topk_label,
        "selected_topk_n": int(selected_topk_n),
        "n_features": int(len(selected_features)),
        "all_candidate_feature_columns_csv": str(all_feat_csv),
        "feature_columns_csv": str(selected_feat_csv),
        "feature_ranking_csv": ranking_csv,
        "feature_hist": str(FEATURE_HIST),
        "label_strict": str(LABEL_STRICT),
        "run_sensitivity_test": RUN_SENSITIVITY_TEST,
        "run_topk_test": RUN_TOPK_TEST,
        "topk_list": TOPK_LIST,
        "final_params": best_params,
    }

    with open(out_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(metrics_out, f, ensure_ascii=False, indent=2)

    final_model.save_model(str(out_dir / "xgb_model.json"))

    imp_gain = final_model.get_score(importance_type="gain")
    df_imp = pd.DataFrame(
        {"feature": list(imp_gain.keys()), "gain": list(imp_gain.values())}
    ).sort_values("gain", ascending=False)
    df_imp.to_csv(
        out_dir / "feature_importance_gain.csv", index=False, encoding="utf-8-sig"
    )

    for split_name, X_split, y_split, pred_split in (
        ("train", X_train, y_train, pred_train),
        ("valid", X_valid, y_valid, pred_valid),
        ("test", X_test, y_test, pred_test),
    ):
        df_pred = X_split.copy()
        df_pred[target_col] = y_split.values
        df_pred["pred"] = pred_split
        df_pred.to_parquet(out_dir / f"pred_{split_name}.parquet", index=False)

    print(f"\n[DONE] {target_col}")
    print(json.dumps(metrics_out, ensure_ascii=False, indent=2))

    return final_model, metrics_out, selected_features


# =========================================================
# 5) MAIN
# =========================================================
def main():
    print("=" * 80)
    print("BCC-CSM2-MR XGBoost training (non-seasonal features)")
    print("=" * 80)
    print(f"[FEATURE_HIST] {FEATURE_HIST}")
    print(f"[LABEL_STRICT] {LABEL_STRICT}")
    print(f"[OUT_ROOT] {RUN_ROOT}")
    print(f"[RUN_SENSITIVITY_TEST] {RUN_SENSITIVITY_TEST}")
    print(f"[RUN_TOPK_TEST] {RUN_TOPK_TEST}")
    print(f"[TOPK_LIST] {TOPK_LIST}")

    run_id = timestamp()
    summary_rows = []

    run_flash = RUN_ROOT / f"FLASH_{run_id}"
    df_flash, feat_cols_flash_all = load_train_table(
        FEATURE_HIST, LABEL_STRICT, TARGET_FLASH
    )
    _, metrics_flash, _ = train_one_target(
        df=df_flash,
        all_feature_cols=feat_cols_flash_all,
        target_col=TARGET_FLASH,
        out_dir=run_flash,
    )
    summary_rows.append(
        {
            "target": TARGET_FLASH,
            "run_dir": str(run_flash),
            "n_all_features": metrics_flash["n_all_features"],
            "selected_topk_label": metrics_flash["selected_topk_label"],
            "selected_topk_n": metrics_flash["selected_topk_n"],
            "n_features": metrics_flash["n_features"],
            "best_iteration": metrics_flash["best_iteration"],
            "train_r2": metrics_flash["train"]["r2"],
            "valid_r2": metrics_flash["valid"]["r2"],
            "test_r2": metrics_flash["test"]["r2"],
            "train_rmse": metrics_flash["train"]["rmse"],
            "valid_rmse": metrics_flash["valid"]["rmse"],
            "test_rmse": metrics_flash["test"]["rmse"],
        }
    )

    run_hail = RUN_ROOT / f"HAIL_{run_id}"
    df_hail, feat_cols_hail_all = load_train_table(
        FEATURE_HIST, LABEL_STRICT, TARGET_HAIL
    )
    _, metrics_hail, _ = train_one_target(
        df=df_hail,
        all_feature_cols=feat_cols_hail_all,
        target_col=TARGET_HAIL,
        out_dir=run_hail,
    )
    summary_rows.append(
        {
            "target": TARGET_HAIL,
            "run_dir": str(run_hail),
            "n_all_features": metrics_hail["n_all_features"],
            "selected_topk_label": metrics_hail["selected_topk_label"],
            "selected_topk_n": metrics_hail["selected_topk_n"],
            "n_features": metrics_hail["n_features"],
            "best_iteration": metrics_hail["best_iteration"],
            "train_r2": metrics_hail["train"]["r2"],
            "valid_r2": metrics_hail["valid"]["r2"],
            "test_r2": metrics_hail["test"]["r2"],
            "train_rmse": metrics_hail["train"]["rmse"],
            "valid_rmse": metrics_hail["valid"]["rmse"],
            "test_rmse": metrics_hail["test"]["rmse"],
        }
    )

    df_summary = pd.DataFrame(summary_rows)
    summary_csv = RUN_ROOT / f"summary_FLASH_HAIL_{run_id}.csv"
    df_summary.to_csv(summary_csv, index=False, encoding="utf-8-sig")

    print("\n" + "=" * 80)
    print("[DONE] BCC-CSM2-MR training and TopK sensitivity finished.")
    print(f"[SUMMARY] {summary_csv}")
    print(f"[OUT] {RUN_ROOT}")
    print("=" * 80)


if __name__ == "__main__":
    main()
